# -*- coding: utf-8 -*-
"""tempat wisata bali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SEvMqGBZ9fGvxp-jLjnpuMIbe-b_-4nu
"""

!pip install pandas
!pip install folium
!pip install matplotlib

import pandas as pd
import folium
from folium.plugins import HeatMap
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

data = pd.read_csv("tempat wisata.csv")
print(data)

# Create map object centered on Bali
map = folium.Map(location=[-8.40876084104688, 115.20105291690847], zoom_start=13)

# Add Heatmap layer
heatmap_data = data[['Latitude', 'longitude']].values.tolist()
HeatMap(heatmap_data, radius=15).add_to(map)

# Add Clustered Marker layer
from folium.plugins import MarkerCluster
marker_cluster =MarkerCluster().add_to (map)
for index, row in data.iterrows():
  folium.Marker([row['Latitude'], row['longitude']], popup=row['Tempat Wisata']+':'+ row['Alamat']).add_to(marker_cluster)

# Display map
map